# Sudoku

- Diseño de agentes inteligentes
- Profesor: Juan Emmanuel Ledesma Martínez
- Equipo 7:
  
| Alumno | Matrícula |
| ---- | ---- |
| Juan Pablo Echeagaray González | A0083646 | 
| Emily Rebeca Méndez Cruz | A00830768 | 
| Oscar Antonio Banderas Álvarez | A01568492 | 
| Erika Martínez Meneses | A01028621 | 
| César Guillermo Vázquez Alvarez | A01197857 |

Fecha: 15 de marzo del 2022

## Instrucciones

En equipos, resuelvan los siguientes tableros de Sudoku utilizando algún algoritmo para problemas de búsqueda con restricciones:

![Tablero 1](img/2022-03-12-21-19-00.png)

![Tablero 2](img/2022-03-12-21-19-17.png)

![Tablero 3](img/2022-03-12-21-19-29.png)

![Tablero 4](img/2022-03-12-21-19-44.png)

La solución de este problema se basó en la explicación que el profesor Thorsten Altenkirch da en un video del canal de YouTube _Computerphile_.

Computerphile. (2020, February 12). Python Sudoku Solver - Computerphile [Video]. YouTube. https://www.youtube.com/watch?v=G_UYXzGuqvM


## Dependencias

In [1]:
# Hace que se vean mejor los tableros en la consola
import numpy as np


## Tableros

In [2]:
board_1 = np.array([[9, 3, 6, 0, 2, 5, 0, 1, 4],
                    [0, 1, 7, 0, 3, 4, 9, 2, 8],
                    [8, 0, 0, 0, 9, 7, 0, 0, 0],
                    [0, 0, 3, 4, 0, 0, 5, 9, 0],
                    [6, 0, 0, 0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 3, 8, 0, 0, 7, 1],
                    [0, 0, 0, 9, 0, 0, 0, 0, 5],
                    [0, 5, 1, 0, 4, 0, 0, 0, 0],
                    [4, 6, 0, 0, 0, 0, 1, 8, 0]])

board_2 = np.array([[0, 0, 0, 8, 0, 7, 9, 1, 0],
                    [9, 0, 0, 3, 4, 0, 2, 0, 0],
                    [0, 0, 5, 0, 0, 0, 0, 7, 0],
                    [5, 9, 3, 7, 0, 2, 0, 6, 4],
                    [0, 0, 1, 0, 0, 0, 0, 3, 8],
                    [8, 7, 0, 6, 3, 1, 0, 9, 2],
                    [7, 4, 0, 0, 0, 0, 0, 2, 0],
                    [0, 0, 0, 0, 0, 4, 3, 0, 0],
                    [0, 5, 2, 1, 7, 0, 0, 0, 0]])

board_3 = np.array([[5, 0, 0, 6, 9, 4, 0, 3, 2],
                    [9, 3, 6, 0, 1, 2, 0, 4, 0],
                    [0, 0, 0, 3, 0, 7, 0, 0, 0],
                    [0, 0, 5, 2, 0, 0, 0, 7, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0, 9],
                    [2, 0, 8, 0, 0, 3, 5, 0, 0],
                    [0, 6, 2, 0, 3, 0, 0, 0, 4],
                    [3, 8, 1, 0, 4, 6, 0, 5, 0],
                    [4, 0, 0, 7, 0, 8, 6, 1, 0]])

board_4 = np.array([[8, 7, 0, 0, 4, 2, 9, 1, 5],
                    [1, 3, 0, 5, 0, 8, 0, 2, 0],
                    [5, 0, 2, 0, 0, 0, 0, 8, 3],
                    [4, 0, 3, 0, 0, 0, 8, 7, 0],
                    [0, 6, 7, 0, 0, 1, 3, 0, 0],
                    [0, 0, 0, 0, 0, 0, 2, 5, 0],
                    [0, 0, 4, 6, 0, 5, 0, 3, 0],
                    [6, 0, 1, 0, 0, 4, 5, 0, 8],
                    [0, 8, 0, 2, 0, 0, 0, 0, 4]])

# Usar esta línea para verificar que los tableros tienen las dimensiones correctas
# board_1.shape == board_2.shape == board_3.shape == board_4.shape == (9, 9)

## Funciones auxiliares

In [3]:
def check_position(value: int, row: int, col: int, board: np.array) -> bool:
    # Function that checks if we can put a number in a position

    # Check if the number is already in the row
    for i in range(0, 9):
        if board[row, i] == value:
            return False

    # Check if the number is already in the column
    for i in range(0, 9):
        if board[i, col] == value:
            return False

    # Check if the number is already in the 3x3 box
    box_row = (row // 3) * 3
    box_col = (col // 3) * 3

    for i in range(box_row, box_row + 3):
        for j in range(box_col, box_col + 3):
            if board[i, j] == value:
                return False

    return True


In [4]:
def solve(board: np.array) -> None:

    # Loop through the board to find empty squares (filled with 0)
    for i in range(0, 9):
        for j in range(0, 9):

            # When we find an empty square, we loop through the numbers 1 to 9
            # to check if we can put a number in that position
            if board[i, j] == 0:
                for n in range(1, 10):
                    if check_position(n, i, j, board):
                        board[i, j] = n

                        # Once we have placed the number, we can call solve recursively
                        solve(board)

                        # Here backtracking happens, the only way we can end up in this position
                        # is if the number we tried lead us to a dead end, so, we take it back and
                        # try another number
                        board[i, j] = 0
                return
    
    print(board)
    input('Press enter to continue...')
    

In [5]:
solve(board_1)


[[9 3 6 8 2 5 7 1 4]
 [5 1 7 6 3 4 9 2 8]
 [8 4 2 1 9 7 6 5 3]
 [1 8 3 4 7 2 5 9 6]
 [6 7 4 5 1 9 8 3 2]
 [2 9 5 3 8 6 4 7 1]
 [7 2 8 9 6 1 3 4 5]
 [3 5 1 7 4 8 2 6 9]
 [4 6 9 2 5 3 1 8 7]]


In [6]:
solve(board_2)


[[4 3 6 8 2 7 9 1 5]
 [9 1 7 3 4 5 2 8 6]
 [2 8 5 9 1 6 4 7 3]
 [5 9 3 7 8 2 1 6 4]
 [6 2 1 4 5 9 7 3 8]
 [8 7 4 6 3 1 5 9 2]
 [7 4 9 5 6 3 8 2 1]
 [1 6 8 2 9 4 3 5 7]
 [3 5 2 1 7 8 6 4 9]]


In [7]:
solve(board_3)


[[5 1 7 6 9 4 8 3 2]
 [9 3 6 8 1 2 7 4 5]
 [8 2 4 3 5 7 1 9 6]
 [1 4 5 2 6 9 3 7 8]
 [6 7 3 5 8 1 4 2 9]
 [2 9 8 4 7 3 5 6 1]
 [7 6 2 1 3 5 9 8 4]
 [3 8 1 9 4 6 2 5 7]
 [4 5 9 7 2 8 6 1 3]]


In [8]:
solve(board_4)


[[8 7 6 3 4 2 9 1 5]
 [1 3 9 5 6 8 4 2 7]
 [5 4 2 1 9 7 6 8 3]
 [4 5 3 9 2 6 8 7 1]
 [2 6 7 8 5 1 3 4 9]
 [9 1 8 4 7 3 2 5 6]
 [7 9 4 6 8 5 1 3 2]
 [6 2 1 7 3 4 5 9 8]
 [3 8 5 2 1 9 7 6 4]]
